### PR TITLE
Various fixes, better error reporting and support for specifying protocols

### PR DESCRIPTION
**Pull request by andreasley**

### CODE REVIEW

**Comment by andreasley** [comment]
Is there a way to run `continuous-integration/travis-ci/pr` again without pushing anything? The current version should build and test fine on both platforms.

**Comment by BrettRToomey** [comment]
@andreasley I restarted the build for you. For future reference: you can click on `Details` next to the Travis build and in the upper-corner of the `build overview` there will be a button that says "Restart Build"

**Comment by andreasley** [comment]
@BrettRToomey  Thanks, that did the trick. I finally also found the button you mentioned. :)

**Comment by BrettRToomey** [comment]
@andreasley Did you get permission to merge this? Otherwise, you usually have to wait for a mod to do this for you.

**Comment by BrettRToomey** [comment]
@LoganWright @tannernelson Do we need to revert this?

**Comment by andreasley** [comment]
@BrettRToomey No, I did not get explicit permission. Still new here and trying to figure out how things work, especially the unspoken rules. I assumed that the ability to merge on this repository indicated that I was meant to merge myself if all tests pass. Sorry if that's not the way it's done. :(

**Comment by BrettRToomey** [comment]
@andreasley No worries, it's happened before (I did it lol). I'm not comfortable enough in this repo to review it and decide on what to do myself, so I called in some of the mods :)

**Comment by loganwright** [comment]
@andreasley no worries, everything is very fixable and everything can be undone. Here's the two main rules for repositories:

Merge: Requires approval of 2 admins, 1 of which must be Tanner or Myself
Release: Tanner or Myself, or explicit permission only

We really appreciate all the work you've been putting in on this stuff, so definitely don't be discouraged in any way. We'll evaluate if this needs a reversion or not and then go forward w/ a release, or further review.

**Comment by andreasley** [comment]
@LoganWright Got it, thanks. :) I suggest adding this information to [CONTRIBUTING.md](https://github.com/vapor/vapor/blob/master/Documents/CONTRIBUTING.md)

**Comment by tanner0101** [comment]
Sorry for not making that clear, @andreasley. We're extra cautious after having been burned a bit before. Sometimes it's really hard to tell what small thing might cause a breaking API change in Swift. 

That being said, this PR looks fine and is good to be tagged as a minor patch. There _is_ a breaking change with the error enum but I doubt many people are doing a `switch` on that. And it's a fairly easy fix.

Some minor tweaks I would have liked to see first are proper formatting of comments and more detailed error messaging  (`Context is nil`, `Unknown` are somewhat vague messages). Any chance you could open up a 2nd PR for those? If not, no worries. I can tackle it next time I'm in there.

Thanks again :)

**Comment by andreasley** [comment]
@tannernelson Thanks; happy to work with all of you on this. I agree that comments and improved error reporting should be next on the list. 

The reason for the `Unknown` error messages is that in some cases, the `tls_*` functions just don't report a detailed error. I wish there was a TLS implementation in pure Swift...

In general, exposing a Vapor server directly to the internet seems to be a bit risky because there's just so much weird traffic and edge-cases.

I should be able to contribute a few more fixes and tests before Vapor switches to the Swift Server API, but I'm not convinced we'll get to the point where it's as safe/stable as putting a nginx reverse proxy in front of it.

**Comment by tanner0101** [comment]
The new TLS library from libressl that we're using here is designed to be fool-proof. So I doubt we have any major flaws in the code here. 

Our current recommendation is to put Vapor behind Nginx. The SSL is mostly here for connecting to other services using the client. 

If we didn't have the Server APIs on the horizon I would be interested in dedicating more time to making this wrapper robust, but it seems it's going to be deprecated in 6 months to a year anyway.

**Pull request merged**
