### PR TITLE
Moving to Perfect SSL and Swift 8-18

### PR DESCRIPTION
**Pull request by edjiang**
Don't merge -- I need people smarter than me & Travis to tell me if I did the right thing here =D

Also gonna ask the Perfect team to use the "COpenSSL" convention as that's asked for by SPM

### CODE REVIEW

**Comment by edjiang** [comment]
Tests pass, and I've asked the Perfect team to move to `COpenSSL` per [this PR](https://github.com/PerfectlySoft/Perfect-OpenSSL/pull/2)

I tried this with SecretSocks and it seems to be able to connect to the Spotify API over SSL properly. 

However, I don't think the potential rename should block from getting this merged. So -- would love to see this reviewed and merged!

**Comment by tanner0101** [comment]
This looks good. Let's just see if @LoganWright wants to merge PR #7 for 0.5. Then let's merge and tag.

**Comment by edjiang** [comment]
Awesome. The one last thing is we need to document a compiler flag to add into XCode when building from there. I'm not quite sure how these search paths work, so looking into it right now.

**Comment by tanner0101** [comment]
Can you paste the flag here? I can add to the Vapor Toolbox like `--ssl` or something.

**Comment by edjiang** [comment]
Docs & travis updated in this branch; it's

Under Project > Build Settings > Library Search Paths, add:

```
$(PROJECT_DIR)/**
```

**Pull request merged**
